const icons = {
    search: require('./search.svg').default,
    close: require('./close.svg').default,
    closeSmall: require('./close-small.svg').default,
    user: require('./user.svg').default,
    category: require('./category.svg').default,
    verticalOption: require('./vertical-option.svg').default,
    horizontalOption: require('./horizontal-option.svg').default,
    like: require('./like.svg').default,
    liked: require('./liked.svg').default,
    comment: require('./comment.svg').default,
    share: require('./share.svg').default,
    popular: require('./popular.svg').default,
    notification: require('./notification.svg').default,
    add: require('./add.svg').default,
    galleryAdd: require('./gallery-add.svg').default,
    arrowDown: require('./arrow-down.svg').default,
    arrowUp: require('./arrow-up.svg').default,
    send: require('./send.svg').default,
    eye: require('./eye.svg').default,
    tick: require('./tick.svg').default,
    trash: require('./trash.svg').default,
    edit: require('./edit.svg').default,
    closeCircle: require('./close-circle.svg').default,
    infoCircle: require('./info-circle.svg').default,
    arrowLeft: require('./arrow-left.svg').default,
    arrowRight: require('./arrow-right.svg').default,
};

export default icons;
